stages:
  - tests
  - deploy_integration
  - debuild
  - pbuilder
  - deploy_package



tests:
   stage: tests
   image: registry.gitlab.si.francetelecom.fr/app-hebex_python/hebex-python-toolbox
   before_script:
    - echo "deb http://ubuntu.packages.install-os.multis.p.fti.net/app all cassandra-drivers/3.7" > /etc/apt/sources.list.d/netstat.list
    - apt-get update
    - apt-get install -y python-cassandra
    - export TZ='Europe/Paris'
    - export PYTHONPATH=$PYTHONPATH:.
   script: python castor_tests/test_castor.py

deploy:
  image: registry.gitlab.si.francetelecom.fr/oihtools/ci:runner
  tags:
    - deploy_automation_prod_shared
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${SSHKEY}")
    - export
  stage: deploy_integration
  script:
    - ssh netstat@netstat.vdev.infra.s1.p.fti.net "rm -rf castor_tests_gitlab; mkdir -p castor_tests_gitlab"
    - scp -r . netstat@netstat.vdev.infra.s1.p.fti.net:~/castor_tests_gitlab/castor
    - ssh netstat@netstat.vdev.infra.s1.p.fti.net "cd ~/castor_tests_gitlab/castor; export PYTHONPATH=$PYTHONPATH:.;python castor_tests/test_castor.py"


Debuild:
  image: pfs-installos-registry.artifactory.packages.install-os.multis.p.fti.net/pfs-installos/pbuilder:latest
  tags: 
    - search
  variables :
    RESULT : "."
    GNUPGHOME: "/gpg_home"
  stage: debuild
  before_script:
    - apt-get update
    - apt-get install -y python-sphinx
    - mkdir /gpg_home
    - 'echo "$GPGPUBLICKEY" | gpg --import'
    - 'echo "$GPGPRIVATEKEY" | gpg --import'
  script:
    # on créer le fichier changes, le tar.gz, etc...
    - debuild -S -sa -i -k${KEY_ID}
    - debsign -S -k${KEY_ID} *_source.changes
  artifacts:
    paths:
      - ./*.dsc
      - ./*.tar.*
      - ./*_source.changes
    
Pbuilder:
  image: pfs-installos-registry.artifactory.packages.install-os.multis.p.fti.net/pfs-installos/pbuilder:latest
  tags: 
    - search
  stage: pbuilder
  before_script:
    - apt-get update
  script:
    # on push le paquet sur le repo pour qu'il build en paquet binaire
    - pbuilder oih amd64 trusty-dev admin build *.dsc
    - mv /var/cache/pbuilder/result/*.deb .
  artifacts: 
    paths:
      - ./*.deb
  


DeployPackage:
  image: pfs-installos-registry.artifactory.packages.install-os.multis.p.fti.net/pfs-installos/pbuilder:latest
  when: manual
  only:
    - master
  variables :
    GNUPGHOME: "/gpg_home"
  tags:
    - pbuilder
  stage: deploy_package
  before_script:
    - apt-get update
    - mkdir /gpg_home
    - 'echo "$GPGPUBLICKEY" | gpg --import'
    - 'echo "$GPGPRIVATEKEY" | gpg --import'
    - apt-get install -y git dput hm-ci-check-push netcat-openbsd  || /bin/true
  script:
    - hm-ci-check-push-client -M dop hebex-castor*_source.changes

